import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Nahueldev',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="text-slate-400">{children}</body>
    </html>
  )
}
